### ISSUE TITLE
paging problem

### ISSUE THREAD

**Issue by flaviofagundes** [NullRefExcep/yii2-datatables#10]
Guys

the pagination always shows the number one and the button next page doesn't work with option 'serverSide' => true.

**Comment by ZAYEC77** [comment]
@flaviofagundes thank for issue, I try to fix it, please check it on your case

**Comment by flaviofagundes** [comment]
Wow!
Now is working!

So fast and efficient!
This is the power of community of open source!
Thanks a lot

**Comment by ZAYEC77** [comment]
@flaviofagundes you're welcome)
