### ISSUE TITLE
Problem with Styling

### ISSUE THREAD

**Issue by flaviofagundes** [NullRefExcep/yii2-datatables#12]
Hi Guys

Just style type that works is the STYLING_DEFAULT.

When i try use another, the layout shows  broken.

Here how i tryed input the configuration at config.php

``` php
'assetManager' => [
            'bundles' => [
                 'nullref\datatable\DataTableAsset' => [
                    'styling' => \nullref\datatable\DataTableAsset::STYLING_BOOTSTRAP,
                  ]
            ],
        ], 
```

**Comment by ZAYEC77** [comment]
@flaviofagundes can You check this bug on native plugin (without yii wrapper)? 
BS assets included but don't work. Maybe problem was not yii widget

**Comment by ZAYEC77** [comment]
@flaviofagundes in BS case I try to fix it to add `tableOptions` in widget call:

``` php
    'tableOptions'=>[
        'class'=>'table table-striped table-bordered',
    ],
```
