### ISSUE TITLE
retrieving relations with datatable

### ISSUE THREAD

**Issue by flaviofagundes** [NullRefExcep/yii2-datatables#13]
Which option has used to retrieve models relations to datatable?

How this:
Post hasOne Author

$model = Post::find()->all();
$model->author->getFullName();

How do it using this widget to datatables?

**Comment by ZAYEC77** [comment]
Very simple but not very good implementation it's to create special getter in post model e.g:

``` php
fucntion getAuthorFullName() 
{
  return $this->author->getFullName();
}
```

**Comment by flaviofagundes** [comment]
Ok, but how i do put this with parameter at widget call?

**Comment by ZAYEC77** [comment]
@flaviofagundes you can use field `authorFullName` (in this case)

**Comment by flaviofagundes** [comment]
So... may you give me a sample?

I had tried

``` php
/*datatable for Users*/
'columns' => [
            ['data'=> 'NmUserStatus',
             'title'=> 'User Status, ]
            ,...
```

in my User model, i used for test

``` php
   /** method to return User Status Name **/
    public function getNmUserStatus()
    {
      return 'Actived';//for test
    } 
```

**Comment by ZAYEC77** [comment]
view:

``` php
<?= \nullref\datatable\DataTable::widget([
    'data'=>\app\models\BlogPost::find()->all(),
    'columns' => [
        'id',
        'title',
        'newTitle',
        'slug'
    ],
    'tableOptions'=>[
        'class'=>'table table-striped table-bordered',
    ],
]) ?>
```

model:

``` php
class BlogPost extends Post
{
    public function getNewTitle()
    {
        return 'New:' . $this->title;
    }

    public function fields()
    {
        return array_merge(parent::fields(), ['newTitle']);
    }
}
```

**Comment by flaviofagundes** [comment]
it works but i can order by this column.

**Comment by flaviofagundes** [comment]
perhaps the better way could be change de method find() used at the action datatables by another with findBySql.

The performance should be better.

**Comment by ZAYEC77** [comment]
@flaviofagundes maybe, in you case it will be better

**Comment by flaviofagundes** [comment]
@ZAYEC77 i'm trying use a method findBySQL, but order columns   and the search don't work

Any suggestion?

``` php

//my model User

class User extends \yii\db\ActiveRecord
{
    public $name_user_status;

    public function fields()
    {
        return array_merge(parent::fields(), ['name_user_status']);
    }

...
//add this relation field at methods rules and attributeLabels
...


//my UserSearch.php
 public static function report(){
        $query = User::findBySql('select u.id_usuario,
                                                u.name,
                                                u.email, 
                                                u.login,
                                                u.id_user_status,
                                                su.name_user_status, 
                                                u.dt_creation,
                                                u.dt_last_acess 
                                     from user u,  
                                            user_status su
                                     where su.id_user_status = u.id_user_status');

        return $query;

    }

//my controller

public function actions()
    {
         return [
             'datatable' => [
                 'class' => 'nullref\datatable\DataTableAction',
                 'query' => \app\modules\base\models\UserSearch::report(),
             ],
         ];
     }    

```

**Comment by ZAYEC77** [comment]
@flaviofagundes thank you for feedback. I think, when you use findBySql, this method set sql to `query`, and after that you can't modify `query` by method like `order` or `where`.
Maybe I'm wrong, I will investigate this question.

**Comment by flaviofagundes** [comment]
@ZAYEC77 thanks for your help.

this issue is the last item to use the datatables for my  datagrid application :)

**Comment by yiqiang** [comment]
I think the key step here in the solution is 

    public function fields()
    {
        return array_merge(parent::fields(), ['newTitle']);
    }

as i investigated if doing the getModels() as suggested, the related data is not fetched. Any other method to do a neater job, instead of specifying this array_merge?

**Comment by yiqiang** [comment]
Hi,

Base on flaviofagundes's comment :

@ZAYEC77 i'm trying use a method findBySQL, but order columns and the search don't work

so how to solve this?

**Comment by ZAYEC77** [comment]
do you want to use order and search at Datatables?
in this case you need to modify your query in functions `applyFilter` and `applyOrder`.
Please, check readme.
