### ISSUE TITLE
Server side issue

### ISSUE THREAD

**Issue by odat** [NullRefExcep/yii2-datatables#15]
hello, 
when i use serverside i get this error message 

Exception 'yii\base\InvalidParamException' with message 'Response content must not be an array.' 

```
     return [
         'datatables' => [
             'class' => 'karauia\datatables\DataTableAction',
             'query' =>  Model::find(),
            'applyOrder' => function($query, $columns, $order) {
            //custom ordering logic
            return $query;
         },
         'applyFilter' => function($query, $columns, $search) {
            //custom search logic
            return $query;
         },
         ],
     ] ; 
```

**Comment by ZAYEC77** [comment]
Hello, by what action did You get this error?

**Comment by odat** [comment]
sorry it work now, please if you can reach the documentation with examples 
Thanks

**Comment by ZAYEC77** [comment]
What kind of examples do You want?

**Comment by odat** [comment]
for example how use relations of columns

**Comment by Setitch** [comment]
function($query, $columns, $search) {
            //custom <type> logic
            return $query;
         },

Just modify this query, like  $query->join.... and so on.
