### ISSUE TITLE
Getting: No matching records found when data is returned

### ISSUE THREAD

**Issue by SigalZ** [NullRefExcep/yii2-datatables#16]
Hello,

I am new to yii.

I am trying to use this widget with no success.

My view has this code:
`<?= \nullref\datatable\DataTable::widget([
            'columns' => [
                'invoice_discount_report__debtor__name',
                'invoices',
                'amount',
                'amount_paid',
                'discount_applied'
            ],
            'serverSide' => true,
        'ajax' => '/api/dashboard/getinvoices/',
             "sAjaxDataProp"=> "datatables"
    ]) ?>`

The js file:
`var myTable = $('#invoicesTbl').DataTable({
        retrieve: true,
        paging: false,
        "language": {
            "emptyTable": "There are no invoices for the company",
        "bProcessing": true,
        "bDestroy": true,
        "sAjaxSource": '/api/dashboard/getinvoices',
        "bAutoWidth": true,
        "aaSorting": [[ 0, "asc" ]],
        "aoColumns": [
            { "bSortable": true, "sWidth": "100%" },
        ],
    }
});

yadcf.init(myTable, [
    {column_number : 0, filter_type: "text", text_data_delimiter: ","}
    ],'footer');
});`

getinvoices function:
`$company_id = Generic::COMPANY_ID;
        $report_type = isset($this->dataBody['report_type'])?$this->dataBody['report_type']:Generic::AV;

```
    if ($company_id === null) 
        $this->sendResponse(501,array('error'=>'Invalid company found'));

    $this->sendResponse(200, [
         'datatables' => [
             'class' => 'nullref\datatable\DataTableAction',
             'query' => InvoiceDiscountReport::getInvoices($company_id, $report_type)
         ],
     ]);`
```

Json array returned:
`{"datatables":{"class":"nullref\\datatable\\DataTableAction","query":[{"invoice_discount_report__debtor__name"
:"BRAD PITT","invoices":"1","amount":"2500.75","amount_paid":"1000.00","discount":"150.00"},{"invoice_discount_report__debtor__name"
:"SIGAL ZAHAVI","invoices":"1","amount":"1000.00","amount_paid":"500.00","discount":"100.00"}]}}`

Yet, the tables says: No matching records found.

What am I doing wrong? Please help, I am trying to solve this for days now.

Thank you very much

**Comment by ZAYEC77** [comment]
@SigalZ  hello, it seems You chose wrong way.
You don't have to create js yourself, widget create it itself.

**Comment by ZAYEC77** [comment]
Only things that You have to do are:
- call widget 
- to declare action in controller

**Comment by SigalZ** [comment]
Hello @ZAYEC77,
Thank you for the quick reply. I removed the js code but still get no matching records found.

View (I removed the table markup):
`<?= \nullref\datatable\DataTable::widget([ 
            'columns' => [ 'invoice_discount_report__debtor__name', 
                'invoices', 
                'amount', 
                'amount_paid', 
                'discount_applied' ], 
            'serverSide' => true, 
            'ajax' => '/api/dashboard/getinvoices/', 
            "sAjaxDataProp"=> "datatables" ]) 
        ?>`

Controller action:
`$this->sendResponse(200, [
         'datatables' => [
             'class' => 'nullref\datatable\DataTableAction',
             'query' => InvoiceDiscountReport::getInvoices($company_id, $report_type)
         ],
     ]);`

JSON response:
`{"datatables":{"class":"nullref\datatable\DataTableAction","query":[{"invoice_discount_report__debtor__name"
:"BRAD PITT","invoices":"1","amount":"2500.75","amount_paid":"1000.00","discount":"150.00"},{"invoice_discount_report__debtor__name"
:"SIGAL ZAHAVI","invoices":"1","amount":"1000.00","amount_paid":"500.00","discount":"100.00"}]}

**Comment by ZAYEC77** [comment]
You can use action from this package
Please, look  the examples in docs

**Comment by ZAYEC77** [comment]
This array must be in method `actions` in controller

**Comment by SigalZ** [comment]
I did look at your examples, and I am using an action: ( 'ajax' => '/api/dashboard/getinvoices')
`<?= \nullref\datatable\DataTable::widget([ 
            'assetManager' => [
                'bundles' => [
                    'nullref\datatable\DataTableAsset' => [
                    'styling' => '\nullref\datatable\DataTableAsset::STYLING_BOOTSTRAP'
                    ]
                ],
            ],
            'columns' => [ 'Customer', 
                'invoices', 
                'amount', 
                'amount_paid', 
                'discount_applied' ], 
            'serverSide' => true, 
            'ajax' => '/api/dashboard/getinvoices', 
            "sAjaxDataProp"=> "datatables",
            ])
        ?>`

"This array must be in method actions in controller" What array? I am sorry, but your examples are not very clear for a noob. 
For me it looks like I am following your example, but I have an action called: actionGetinvoices and not actions, is that the problem?

My code now:

controller:
`public function actionGetinvoices() {
        $company_id = Generic::COMPANY_ID;
        $report_type = isset($this->dataBody['report_type'])?$this->dataBody['report_type']:Generic::AP;

```
    if ($company_id === null) 
        $this->sendResponse(501,array('error'=>'Invalid company found'));

    $json = 
     [
         'datatables' => [
             'class' => 'nullref\datatable\DataTableAction',
             'query' => InvoiceDiscountReport::getInvoices($company_id, $report_type),
             'applyOrder' => function($query, $columns, $order) {
                //custom ordering logic
                return $query;
             },
             'applyFilter' => function($query, $columns, $search) {
                //custom search logic
                return $query;
             },
         ],
    ];

    $this->sendResponse(200, $json);
    `
```

My view:
`<?= \nullref\datatable\DataTable::widget([
    'columns' => [
        'customer',
        'invoices',
        'amount',
        'amount paid',
        'discount'
    ],
    'serverSide' => true, 
    'ajax' => '/api/dashboard/getinvoices',
    "sAjaxDataProp"=> "datatables"
]) ?>`

Respones:
`{"datatables":{"class":"nullref\\datatable\\DataTableAction","query":[{"customer":"BRAD PITT","invoices"
:"1","amount":"2500.75","amount_paid":"1000.00","discount":"150.00"},{"customer":"SIGAL ZAHAVI","invoices"
:"1","amount":"1000.00","amount_paid":"500.00","discount":"100.00"}],"applyOrder":{},"applyFilter":{
}}}`

No Matching records found.

**Comment by ZAYEC77** [comment]
You have to use `nullref\datatable\DataTableAction` or extend it.
Action has to return data, but your action return config of another action (it's wrong).
If you want to give more help, you can contact with me by email.
