### ISSUE TITLE
formatter

### ISSUE THREAD

**Issue by byusufw** [NullRefExcep/yii2-datatables#17]
how do i apply formatter for a spesific collumn? in example I want to format date or number from the retrieved data

thanks for response

**Comment by ZAYEC77** [comment]
Hello, do you want to use server-side?

**Comment by byusufw** [comment]
yes I do

**Comment by alladas** [comment]
Hi @byusufw,
Did you find how to use formatter?
This will make it easier.

**Comment by ZAYEC77** [comment]
I recommend to use custom getters in your models.
