### ISSUE TITLE
Ordering and filtering sample

### ISSUE THREAD

**Issue by alladas** [NullRefExcep/yii2-datatables#19]
Hello Guys,
I am looking for an example of custom ordering  and filtering logic with a 'serverSide' option enabled?
That will be great to get a sample of a working sample.
@ZAYEC77 Bravo. Seems great.
In advance thanks.

**Comment by ZAYEC77** [comment]
@alladas Hello, try to do it ASAP.

**Comment by alladas** [comment]
@ZAYEC77 Many thanks to you.
I gave it a try using actions as you provided in my model but it is not working.

**Comment by Setitch** [comment]
@alladas - here - my example of sorting|
                 'applyOrder' => function($query, $columns, $order) {
                    //custom ordering logic

```
                $model = new \YourModelNamespaceHere();
                foreach ($order as $o) {
                    if (isset($columns[$o['column']])) {
                        if (array_key_exists($columns[$o['column']]['data'], $model->attributes)) {
                            if ($o['dir'] == 'asc')
                                $query -> orderBy($columns[$o['column']]['data'] . ' asc');
                            else
                                $query -> orderBy($columns[$o['column']]['data'] . ' desc');
                        }
                    }
                }
                return $query;
             },
```

**Comment by ZAYEC77** [comment]
@Setitch can you make PR with your example, if it is correct?

**Comment by alladas** [comment]
@Setitch  - Sorry for the delay,
The [built-in applyOrder](https://github.com/NullRefExcep/yii2-datatables/blob/master/src/DataTableAction.php#L100) method is enough for your custom ordering logic.
Meaning you don't need it at all.
I think a custom ordering logic is needed only for non typical cases.
But if you are after a default ordering, you may try this:

```
DataTable::widget([
    'id'=>'your-id',
    'serverSide' => true,
    'processing' => true,
    'order' => [[X, 'desc' ]],` // replace X par the position of your column => integer
    ......
]);
```

Hope this helps.

**Comment by Setitch** [comment]
@alladas your example only works for basic sorts, mine works for all basic sorsts (you can even make a dfefault there) also a bit more complex (as im using VIEW not TABLE on which i made a query.

But thanks, didnt knew you could use 'order' as parameter - they are not documented for this plugin.

**Comment by ZAYEC77** [comment]
@Setitch  "they are not documented for this plugin" because it's Datatables option
Please, look [docs](https://datatables.net/reference/option/order)
Widget supports every option.

**Comment by Setitch** [comment]
But it might mean (not documented or spoken _) that this plugin do not support them

**Comment by ZAYEC77** [comment]
@Setitch I think this section will be enough ([docs](https://github.com/NullRefExcep/yii2-datatables/blob/master/README.md#datatable-options))
