### ISSUE TITLE
ServerSide with paging

### ISSUE THREAD

**Issue by alladas** [NullRefExcep/yii2-datatables#20]
Hello @ZAYEC77,
Hello All,

How to get serverSide work with paging?
Trying it with the basic example seems not working. 
Got 10 displayed out of 2000+ without any pagination.
Just like in this screenshot.
![missing_paging](https://cloud.githubusercontent.com/assets/11385698/15013090/9a24d4ca-11fd-11e6-8e74-bf51c9b042a0.png)

In advance thanks.

**Comment by ZAYEC77** [comment]
Hello, thanks for issue.
@alladas an you provider code that you use?

**Comment by alladas** [comment]
Hello @ZAYEC77,
Thanks for your answer.
Here is what I have tried. It is a basic setting. Just for testing according to your instructions.
`=== Model ===
public static function find()
    {
        return new ModelQuery(get_called_class());
    }

=== ModelController ===
public function actions() {
    return [ 
        'datatables' => [ 
            'class' => DataTableAction::className(),
            'query' => Model::find (),
        ] 
    ];
}

=== index ===
<?= \nullref\datatable\DataTable::widget([
        'serverSide' => true,
        'processing' => true,
        'language' => [
            'lengthMenu' => Yii::t('common', 'Showing').' _MENU_ '.Yii::t('common', 'records per page'),
            'searchPlaceholder'=>Yii::t('common', 'Search'),'class'=>'input-group input-group-sm',
            'paginate' => [
                'first' => Yii::t('common', 'First'),
                'previous' => Yii::t('common', 'Previous'),
                'next' => Yii::t('common', 'Next'),
                'last' => Yii::t('common', 'Last'),
            ],
            'info' => Yii::t('common', 'Showing').' _START_ '.Yii::t('common', 'to').' _END_ '.Yii::t('common', 'of').' _TOTAL_ '.Yii::t('common', 'entries'),
            'processing' => '<i class="fa fa-spinner fa-pulse fa-3x fa-fw margin-bottom"></i><span class="sr-only">'.Yii::t('common', 'Loading...').'</span>'
        ],
        'ajax' => Url::to(['controller/datatables']),
        'columns' => [
        [
            'data' => 'model_id',
            'title' => Yii::t('backend', 'Id'),
        ],
            [
                'data' => 'parent_id',
                'title' => Yii::t('backend', 'Parent'),
            ],
            'title',
            'description',
            [
                'data' => 'start',
                'title' => Yii::t('backend', 'From')
            ],
            [
                'data' => 'end',
                'title' => Yii::t('backend', 'Thru')
            ],
        ],
    ]);
    ?>
`

**Comment by alladas** [comment]
Hello @ZAYEC77,
After some minor changes in DataTableAction server side is working for me.
Pagination, Search and sort seems now ok.
Posted my changes here: [https://github.com/alladas/yii2-datatables/commit/56dd35c230082fbf181be3c24bcfde944c6831ca](url)
First PR?
Thanks.

**Comment by ZAYEC77** [comment]
Hello, please make pull request if all works fine.

**Comment by alladas** [comment]
Thanks @ZAYEC77 ,
Ok, I will do that after more tests.
May I have one trivial question data formatting?
Is it possible to use Yii formatter?
I really appreciate your reactivity.

**Comment by ZAYEC77** [comment]
@alladas I think it would be implemented by afterAction method in your application (I'm not sure, but think that it can help you to format response data).
It's not very common case for adding to package.
If you implement this, you can add example to README.

**Comment by ZAYEC77** [comment]
@alladas also you can use event `afterAction` and modify `result` value.

**Comment by alladas** [comment]
Yes I tested yesterday with afterFind it worked.
But then, the column get sorted as string.
That is why I wonder if there is a another way .
Also using afterFind leads to many changes since I was already using yii formatter on these fields.

**Comment by fjqtp** [comment]
Hi All,

pagination still doesn't work for me, all records are shown in table. I noticed that it's fixed when I rearrange 67 and 68-70 lines in DataTableAction.php (sorry not familiar with git to post changes like alladas did, it's about cloning $filterquery AFTER setting offset and limit).

Can you please check if it helps?

**Comment by alladas** [comment]
Hi @fjqtp ,
Maybe I can help but I am not sure to understand well: 

> pagination still doesn't work for me, all records are shown in table

May you post a screenshot?

**Comment by fjqtp** [comment]
![scr](https://cloud.githubusercontent.com/assets/15140455/16481423/68510fd6-3ed5-11e6-9071-e8dec1f314bf.png)

Please check screenshot. All 32 entries are shown though it says "1 to 10". When I go to 2 page, it shows exactly the same entries here.

**Comment by ZAYEC77** [comment]
@fjqtp Hello, do you use dev version?

**Comment by fjqtp** [comment]
@ZAYEC77 yes.

**Comment by Setitch** [comment]
I have the same problem, after reading the file and the solution from https://github.com/alladas/yii2-datatables/commit/56dd35c230082fbf181be3c24bcfde944c6831ca i can assure that this solution works. Also this solution two month old, so project owner - commit it, or i dont see any reason for using any further version of your package.

**Comment by ZAYEC77** [comment]
@Setitch Hello, this commit is the same as master of current repository [DataTableAction.php:71](https://github.com/NullRefExcep/yii2-datatables/blob/master/src/DataTableAction.php#L71)

Ping me if you have any problems.

**Comment by Setitch** [comment]
Then make a package of it - as if you install the package from composer - its still old one - can you update it then?

**Comment by ZAYEC77** [comment]
@Setitch you can use `dev-master`.
But if need I can make new release

**Comment by ZAYEC77** [comment]
Hey, guys, can I close this issue?

**Comment by Setitch** [comment]
@ZAYEC77 this should already be packaged as stable as it is. On DEV you should only have things that are in development and shouldnt be used on production yet.

**Comment by ZAYEC77** [comment]
@Setitch you a right, please, use new [version](https://github.com/NullRefExcep/yii2-datatables/releases/tag/v1.0.1).
