### ISSUE TITLE
Cannot add other column types

### ISSUE THREAD

**Issue by Setitch** [NullRefExcep/yii2-datatables#22]
As in subject

**Comment by ZAYEC77** [comment]
@Setitch please, give the example of usage widget with custom column types?
How you see this case?

**Comment by Setitch** [comment]
Mostly i need to add details opener, what you can only add are links, which are not exactly enought, i have more than 10 datatables on board, so i need to put something there - like constant string, or similar

**Comment by ZAYEC77** [comment]
Please, give the example of usage widget in your code and we can implement this feature.

**Comment by Setitch** [comment]
I want to create other ,,rendered'' collumn, but i cannot. The only one rendered is already written and used by that columnclass and thats all....

**Comment by Setitch** [comment]
Ok, i hacked it around with quite much code but it works^^, its not very nice looking, but you can close it

**Comment by ZAYEC77** [comment]
@Setitch you can look example of custom column in [LinkColumn](https://github.com/NullRefExcep/yii2-datatables/blob/master/src/LinkColumn.php).
You have to set `render` properties to you column object.
This properties will be using by [DataTables](https://datatables.net/examples/ajax/null_data_source.html) for rendering.
