### ISSUE TITLE
Once more server side pagination is not working....

### ISSUE THREAD

**Issue by Setitch** [NullRefExcep/yii2-datatables#23]
I downloaded the newest package, and that was bad. There were already working code for server side by alladas, i dont know how did you managed to that, but upgrading to yours newest version messed up server side response. [Forking and updating to his code now and packaging, as i cannot allow production servers to stop working due to some not tested upgrades]

**Comment by ZAYEC77** [comment]
@Setitch Sorry, I didn't understand, stable version has diff with alladas version?

**Comment by Setitch** [comment]
Yes, pagination once more didnt worked, and DataTables got all records at once... I now forked your version and added alladas fix and ques what - it works 100% properly.

**Comment by ZAYEC77** [comment]
How you get this package? (by composer, or download)

**Comment by Setitch** [comment]
composer

**Comment by ZAYEC77** [comment]
Can you check version of package on your server?
Maybe problem connect with composer cache?

**Comment by Setitch** [comment]
1.0.1 - sorry i really dont have time for (not now nor in future) to deal with broken packages - already forked, and packaged proper changes, now i fix namespaces and thats all for stability for me.

**Comment by ZAYEC77** [comment]
@Setitch okay, but if you want you can make PR to fix this problem

**Comment by Setitch** [comment]
Sorry, i really do not have time to maintain others packages (nor i can), i already made a fork and working package - i will try to keep with patches you made, but i cannot allow my clients to make ,,composer update'' and from version 1.0.0 to 1.0.1 broke whole application

**Comment by ZAYEC77** [comment]
@Setitch I looked to your commits, but didn't see any functional changes of source code, only changes in namespace and readme.
What diff is between our package and your?

**Comment by Setitch** [comment]
Found out the problem, fixed it and pulled here. For now i will use my package, if you fix all, i will switch, but for now i cannot allow any disrupts when i try to hack my way into 4 scripts at once.

**Comment by ZAYEC77** [comment]
@Setitch thanks for PR.
