### ISSUE TITLE
Empty table is generated

### ISSUE THREAD

**Issue by tigran-k** [NullRefExcep/yii2-datatables#25]
Hi guys,

Thanks for the extension you created. I have just installed it but cannot use it properly.

I have copied following part of code into my index.php file where I generate table with use of GridView widget but your code generates just 

 `<table id="w0"></table>`

 without any data in it. Could you please help me?

```
<?= \nullref\datatable\DataTable::widget([
    'data' => $dataProvider->getModels(),
    'columns' => [
        'id',
        'name',
        'email'
    ],
]) ?>
```

**Comment by ZAYEC77** [comment]
@tigran-k hello, do you have records in DB table?

**Comment by ZAYEC77** [comment]
What version of package do you use?

**Comment by tigran-k** [comment]
I have records in DB table because Yii2 Gridview widget correctly displays the data on the same page and I use "nullref/yii2-datatables": "~1.0"

**Comment by ZAYEC77** [comment]
@tigran-k can you show $dataProvider config?

**Comment by tigran-k** [comment]
```
public function actionIndex()
    {
        $searchModel = new UserSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }
```

**Comment by ZAYEC77** [comment]
Can you check that `$dataProvider->getModels()` return correct array of records?

**Comment by tigran-k** [comment]
<?php var_dump($dataProvider->getModels());die; ?> displayed all user data

**Comment by ZAYEC77** [comment]
I have work example with ActiveDataProvider:

``` php
<?= \nullref\datatable\DataTable::widget([
    'data' => (new \yii\data\ActiveDataProvider([
        'query' => app\models\BlogPost::find(),
    ]))->getModels(),
    'columns' => [
        'id',
        'title',
    ],
]) ?>
```

Please, try this way.

**Comment by ZAYEC77** [comment]
Also I recommend to clear composer cache and update vendors.

**Comment by tigran-k** [comment]
Sorry to say that it did not helped

**Comment by ZAYEC77** [comment]
Try this example:

``` php
<?= \nullref\datatable\DataTable::widget([
    'data' => [
        ['id' => 1, 'title' => 'Test1'],
        ['id' => 2, 'title' => 'Test2'],
    ],
    'columns' => [
        'id',
        'title',
    ],
    'tableOptions' => [
        'class' => 'table table-striped table-bordered',
    ],
]) ?>
```

**Comment by tigran-k** [comment]
Here is what It generated:
`<table id="w1" class="table table-striped table-bordered"></table>`

**Comment by ZAYEC77** [comment]
What version of php do you use?
Do you have installed all common modules?

**Comment by tigran-k** [comment]
PHP 5.6.23, Yes and I use advanced version of Yii2

**Comment by ZAYEC77** [comment]
Do you have any errors in devtools console?

**Comment by tigran-k** [comment]
There are no any errors, I can send you my teamviewer details via email if it will help.

**Comment by ZAYEC77** [comment]
Yes, sure.

**Comment by harikrishnanng** [comment]
@ZAYEC77  I'm getting this same issue. How did you solve it?
output => `<table id="w0"></table>`

php vr: 5.6.15
I'm using yii2 advanced latest.

**Comment by ZAYEC77** [comment]
Hello @harikrishnanng, maybe you have some errors in js?

**Comment by harikrishnanng** [comment]
There were some errors with some of the included js files. I tried using renderPartial(). Still nothing works.

**Comment by ZAYEC77** [comment]
Datatable could not work when you have problems with other js code.

**Comment by harikrishnanng** [comment]
There were no errors in when i used renderPartial().

**Comment by ZAYEC77** [comment]
could you provider code of widget call?

**Comment by harikrishnanng** [comment]
Controller :
```
public function actionCategorys()
    {
      $model = new Category();

      $dataProvider = new ActiveDataProvider([
                                             'query' => Category::find(),
                                             'pagination' => array('pageSize' => 10),
                                             ]);
      if($model->load(Yii::$app->request->post()) && $model->validate()) {

         $this->redirect('categorymanagement',302);
     }
     return $this->renderPartial('categorys',array('model'=>$model, 'categoryTab' => $dataProvider));
}
```

View:
```
<div id="datatab">
			<?= \nullref\datatable\DataTable::widget([
			                                         'data' => $categoryTab->getModels(),
			                                         'columns' => [
			                                         'Category_ID',
			                                         'Category_Name',
			                                         'Category_Desc'
			                                         ],
			                                         ]) ?>
</div>
```

**Comment by ZAYEC77** [comment]
which version of plugin do you use?

**Comment by harikrishnanng** [comment]
Latest from packagist. 
v1.0.2

**Comment by ZAYEC77** [comment]
okay, I try create working example for you

**Comment by harikrishnanng** [comment]
ok. Thanks

**Comment by ZAYEC77** [comment]
When you use `renderPartial` it doesn't include assets files.

I tried to use `render` and get workable solution.

And check this:
https://github.com/ZAYEC77/dt-test

**Comment by harikrishnanng** [comment]
@ZAYEC77 Thanks man

**Comment by harikrishnanng** [comment]
@ZAYEC77 How to add a 'serial no.' column (# 1, 2 3,..) to the table and also some custom columns that are not in the database.?

**Comment by ZAYEC77** [comment]
@harikrishnanng you could set any data to display. There are no special columns for it.
Also, you could look default tools from Datatables plugin.
