### ISSUE TITLE
QUERY FROM ARRAY PROVIDER

### ISSUE THREAD

**Issue by ElijahGM** [NullRefExcep/yii2-datatables#26]
I have saved my data as array in the datatable how do i go about rendering my datatable

**Comment by ZAYEC77** [comment]
@EsoftsLimited hello, can you give example?

**Comment by ElijahGM** [comment]
Sorry I am using mongodb to save my data, in one columns i have an array of item (I did not want to create separate table (Collection) for this kind of data because its is dynamic.

The array is a collection of  associative array example

```
[
  [name=>'Me','attr'=>'XC'],
  [name=>'You','attr'=>'VBC'],
 .....
]
```

I want to create a gridview from arrayDataprovider, how do i do this using your plugin?

**Comment by ElijahGM** [comment]
Secondly on the class DatatableAction you have explicitly used `yii\db\ActiveQuery` and because i am using `yii\mongodb\ActiveQuery`  it cannot be rendered, if i remove the namespace declaration `yii\db\ActiveQuery`  it works, can you update it to make it generic?

**Comment by ZAYEC77** [comment]
You don't have to use ActiveQuery, you can set any possible data if you need.

But when you use server-side, it's better to use own action. 
It's not possible to rework existing action  (I mean `nullref\datatable\DataTableAction`) for your purposes.
It will be easier to create separate action.

In case, when you don't use server-side, you can set any array of data.

**Comment by ElijahGM** [comment]
Understood, can you show an example of how i will customize server side columns?

**Comment by ElijahGM** [comment]
Like for status i would like to wrap it up using labels

**Comment by ZAYEC77** [comment]
As I can understand you want to set columns labels?

If yes, try this:

``` php
<?= \nullref\datatable\DataTable::widget([
    'data' => $model->getData(),//return array from you example
    'columns' => [
        ['data' => 'name', 'title' => 'Name'],
        ['data' => 'attr', 'title' => 'Attribute'],
    ],
]) ?>
```

**Comment by ZAYEC77** [comment]
@EsoftsLimited did you solve problem?
