### ISSUE TITLE
Delete confirmation doesn't work.

### ISSUE THREAD

**Issue by tplk** [NullRefExcep/yii2-datatables#27]
So I'm using this column to display delete action link. But there is no action confirmation when I press it. Custom column with actions in GridView does work though. Any ideas how to fix this? My guess is it's something to do with yii js generation, but I'm not very familiar with framework yet.

```
[
    'class' => 'nullref\datatable\LinkColumn',
    'url' => ['/product/delete'],
    'options' => [
        'id' => 'link-delete',
        'title' => Yii::t('yii', 'Delete'),
        'data-confirm' => Yii::t('yii', 'Are you sure to delete this item?'),
        'data-method' => 'post',
    ],
    'queryParams' => ['id'],
    'label' => '<span class="fa fa-trash-o"></span>',
],
```

I came up with the following solution btw:

```
[
    'class' => 'nullref\datatable\LinkColumn',
    'url' => ['/product/delete'],
    'options' => [
        'id' => 'link-delete',
        'onclick' => "return confirm('Are you sure to delete this item?');",
    ],
    'queryParams' => ['id'],
    'label' => '<span class="fa fa-trash-o"></span>',
],
```

**Comment by ZAYEC77** [comment]
Hello.
Do you have data-confirm attribute in link tag in generated html code?

**Comment by ZAYEC77** [comment]
I and get confirm message with this code:

``` php

        [
            'class' => 'nullref\datatable\LinkColumn',
            'url' => ['/model/delete'],
            'options' => ['data-confirm' => 'Are you sure you want to delete this item?', 'data-method' => 'post'],
            'queryParams' => ['id'],
            'label' => 'Delete',
        ],
```

Maybe you have some other errors in your js.

**Comment by tplk** [comment]
@ZAYEC77 I do have data-confirm attribute, but it doesn't work.
`<a id="link0" href="/?id=2" data-confirm="Are you sure you want to delete this item?" data-method="post">Delete</a>`
I think it happens because I get data using ajax after page is loaded. Probably need to call a function to bind onClick events after dataTables loads data.
I guess we can close this issue. Thanks for your help.

**Comment by ZAYEC77** [comment]
Yes, it can be caused ajax content loading.
But I use code example with server side and it works.

**Comment by ZAYEC77** [comment]
@t-p-l-k 
Also, you can look on my demo project:
https://gitlab.com/nullrefex/app4/blob/master/src/views/site/list.php#L34

**Comment by tplk** [comment]
@ZAYEC77 thank you!
