### ISSUE TITLE
Error while installing package

### ISSUE THREAD

**Issue by iomarmochtar** [NullRefExcep/yii2-datatables#28]
Hello,

i got the problem when do the installation due datatables asset in bower repository is not found

> Problem 1
    - nullref/yii2-datatables v1.0.2 requires bower-asset/datatables ~1.10 -> no matching package found.
    - nullref/yii2-datatables v1.0.1 requires bower-asset/datatables ~1.10 -> no matching package found.
    - nullref/yii2-datatables 1.0 requires bower-asset/datatables ~1.10 -> no matching package found.
    - Installation request for nullref/yii2-datatables ^1.0 -> satisfiable by nullref/yii2-datatables[1.0, v1.0.1, v1.0.2].

After i searching to https://datatables.net/manual/installation#Bower the name of package has been changed to **datatables.net**  not **datatables** anymore.

**Comment by ZAYEC77** [comment]
Hello, @iomarmochtar.

Thanks for your issue.

I have changed bower dependencies to:
```
        "bower-asset/datatables.net": "~1.10",
        "bower-asset/datatables.net-plugins": "~1.0"
```

It should works.

Please, check it.

**Comment by iomarmochtar** [comment]
Still no luck,

```
$ composer require nullref/yii2-datatables:dev-master

  Problem 1
    - Installation request for nullref/yii2-datatables dev-master -> satisfiable by nullref/yii2-datatables[dev-master].
    - nullref/yii2-datatables dev-master requires bower-asset/datatables.net ~1.10 -> no matching package found.
```

You may see the list of datatables.net version on https://libraries.io/bower/datatables.net

**Comment by ZAYEC77** [comment]
@iomarmochtar do you have installed `fxp/composer-asset-plugin`?

**Comment by iomarmochtar** [comment]
Sorry i forgot to install it. 

the plugin successfully installed. 

**thank you.**
