### ISSUE TITLE
Bootstrap style, doesnt display as expected in table element

### ISSUE THREAD

**Issue by mavelar** [NullRefExcep/yii2-datatables#29]

**Comment by ZAYEC77** [comment]
Hello, can you give some code example and screenshot?

**Comment by mavelar** [comment]
![image](https://cloud.githubusercontent.com/assets/737470/25073481/19b19ca6-22a5-11e7-9e59-63c1a0c1c825.png)

`<?= DataTable::widget([
                        'data' => $dataProvider->getModels(),
                        'info' => false,
                        'columns' => [
                            'id',
                            'name',
                            'email'
                        ],
                    ]) ?>`

**Comment by ZAYEC77** [comment]
Did you use this [example](https://github.com/NullRefExcep/yii2-datatables#styling)?

**Comment by leandemon** [comment]
Bootstrap tables require the class 'table', so you'll need to add the 'table' class using tableOptions via the widget config. I also had to set the table width to 100% (which may not be necessary, but was in my case).

Example:
```
<?= \nullref\datatable\DataTable::widget([
    'data' => $dataProvider->getModels(),
    'tableOptions' => [
        'class' => 'table',
        'style' => 'width: 100%',
    ],
    'columns' => [
        'id',
        'name',
        'email'
    ],
]) ?>
```

**Comment by ZAYEC77** [comment]
@leandemon thanks for the comment
Could you add this notice to readme?
I think it will be useful
