### ISSUE TITLE
Search improvment 

### ISSUE THREAD

**Issue by irekbar** [NullRefExcep/yii2-datatables#3]
DataTableAction, line:

```
$dataProvider->query = $actionQuery->andWhere($originalQuery->where);
```

empty AND condition is created when original query is empty, and finally it generate SQL error.
I changed it to:

```
$dataProvider->query = empty($originalQuery->where) ? $actionQuery : $actionQuery->andWhere($originalQuery->where);
```

**Comment by ZAYEC77** [comment]
@irekbar, what is value of `$originalQuery->where` in your case?
I don't get error when set empty string, `null` or `false` in `$originalQuery->where`
Do you use last stable version of framework?

**Comment by serhiivinichuk** [comment]
Fixed.
