### ISSUE TITLE
Wrong bower asset

### ISSUE THREAD

**Issue by shershennm** [NullRefExcep/yii2-datatables#31]
Now `bower-asset/datatables.net` links to https://github.com/DataTables/Dist-DataTables , not to https://github.com/DataTables/DataTables

**Comment by ZAYEC77** [comment]
Do you have some problems with this?

**Comment by shershennm** [comment]
Yes. Frontend resources at `src\DataTableAsset` link to non-existent files

**Comment by shershennm** [comment]
#32

**Comment by ZAYEC77** [comment]
Your PR is merged. Check now.

**Comment by shershennm** [comment]
Thank you for such fast response! All is great now

**Comment by ZAYEC77** [comment]
Thank you too.
