### ISSUE TITLE
Encode field value

### ISSUE THREAD

**Issue by saranvarma** [NullRefExcep/yii2-datatables#34]
'columns' => [
         'feedback_name',
         'created_by',
         'assigned_to',
          'assignment_activity_status',
          'added_date',
           [
                'class' => 'nullref\datatable\LinkColumn',
                 'url' => ['intandem/view'],
                 'queryParams' => ['id'],               -------------> Here i have to pass encoded id field value.
                  'label' => 'View',
             ],
 ],

i want to encode id field value in action column . how can i do this . In queryParams i have to pass encoded value of id field. Please let me know the work around.

**Comment by ZAYEC77** [comment]
Hello.
Do you want pass id of row?

**Comment by saranvarma** [comment]
Yes . iam getting 84 as id . But i want to encode that value and pass to url like intandem/view?id=XSD4$56 . But not 84 as id param value

**Comment by ZAYEC77** [comment]
Try to use `render` parameter at `LinkColumn` class.
Also, check the source code of this class for [example](https://github.com/NullRefExcep/yii2-datatables/blob/master/src/LinkColumn.php#L35).

**Comment by ZAYEC77** [comment]
Something like this:
```
    'columns' => [
        'id',
        'title',
        [
            'class' => 'nullref\datatable\LinkColumn',
            'render' => new JsExpression('function render(data, type, row, meta ){
                return "<a href=\"/custom/url/"+row["id"]+"\">View</a>"
            }'),
        ],
    ],
```
