### ISSUE TITLE
How to use related table data

### ISSUE THREAD

**Issue by yiqiang** [NullRefExcep/yii2-datatables#35]
class Order extends ActiveRecord
{
    public function getCustomer()
    {
        return $this->hasOne(Customer::className(), ['id' => 'customer_id']);
    }
}

Now i want to make a datatable to show customer name with order id, how can i do that?

**Comment by ZAYEC77** [comment]
Hello, please check this issue https://github.com/NullRefExcep/yii2-datatables/issues/13

**Comment by yiqiang** [comment]
Thank you for support, but then how to do the ordering as mentioned in the last few comments

**Comment by ZAYEC77** [comment]
@yiqiang not sure that understand you.
What do you mean?
If you need set some order you can do it in your query.
