### ISSUE TITLE
Change object to baseObject

### ISSUE THREAD

**Issue by yiqiang** [NullRefExcep/yii2-datatables#36]
As in php7.2 object is restricted word and causing Fatal error: Cannot use 'Object' as class name as it is reserved, hence we need to change for yii2 version 2.0.13.1

class LinkColumn extends \yii\base\Object

to

class LinkColumn extends \yii\base\baseObject

Please check and update, thank you

**Comment by ZAYEC77** [comment]
excuse me for large delay
@yiqiang could you check the updated version?
