### ISSUE TITLE
Error while installing package

### ISSUE THREAD

**Issue by akbarkhawaja** [NullRefExcep/yii2-datatables#37]
composer require nullref/yii2-datatables gives the following errors:

Your requirements could not be resolved to an installable set of packages.                               

  Problem 1
    - nullref/yii2-datatables v1.0.4 requires bower-asset/datatables ~1.10.15 -> no matching package found.
    - nullref/yii2-datatables v1.0.3 requires bower-asset/datatables.net ~1.10 -> no matching package found.
    - nullref/yii2-datatables v1.0.2 requires bower-asset/datatables ~1.10 -> no matching package found.
    - nullref/yii2-datatables v1.0.1 requires bower-asset/datatables ~1.10 -> no matching package found.
    - nullref/yii2-datatables 1.0 requires bower-asset/datatables ~1.10 -> no matching package found.
    - Installation request for nullref/yii2-datatables ^1.0 -> satisfiable by nullref/yii2-datatables[1.0, v1.0.1, v1.0.2, v1.0.3, v1.0.4]

The datatables package name has been changed on bower. Probably that is causing the issue

**Comment by ZAYEC77** [comment]
Hello @akbarkhawaja 
Could you show your composer.json?
Do you use fxp plugin or https://asset-packagist.org/ ?

**Comment by akbarkhawaja** [comment]
Yes, I am using fxp plugin 1.4.1

**Comment by akbarkhawaja** [comment]
I cleared composer cache. Updated composer globally, update the fxp plugin to latest 1.4.3 and then attempt again and it worked. The question that is still unanswered, why initially composer was unable to find the matching package.

**Comment by ZAYEC77** [comment]
I think it's your local environment issue.
