### ISSUE TITLE
display relational field by using custom column

### ISSUE THREAD

**Issue by rupalgohel** [NullRefExcep/yii2-datatables#39]
I want to display relational field
```

 <?= \nullref\datatable\DataTable::widget([
         'tableOptions' => [
            'class' => 'table',
            'style' => 'width: 100%',
        ],
        'data' => $dataProvider->getModels(),
        'scrollY' => '200px',
        'scrollCollapse' => true,
        'paging' => true,
        'columns' => [
            [
                'label' => 'Bill / Invoice No', 
                'value' => function($data) { 
                     $invoice1 =$model->invoice->invoiceId ; 
                    return $invoice1; 
                },
            ], 
            'bookingId',
            'name'
        ],
]) ?>
```
how fetch relational field like $model->invoice->invoiceId, current model has relation with Invoice Model

**Comment by ZAYEC77** [comment]
Hello @rupalgohel 
I think you should use `$data` instead `$model` in your closure:
```php
function ($data) { 
    $invoice1 = $data->invoice->invoiceId; 
    return $invoice1; 
}
```

**Comment by rupalgohel** [comment]
` [
                'title' => 'Bill / Invoice No', 
                'data' =>   'bookingId',
                 
            ],`

same table field is working here but i need to use its realtional value means
public function getCustomer()
    {
        return $this->hasOne(front::className(), ['customerId' => 'customerId']);
    }
I want to have Customer name from Customer table and it has relation with booking table.
however I should get like this
 ` [
                'title' => 'Customer Name', 
                'data' =>   function ($data) { 
                $custName = $data->customer->customerName; 
               return $custName; 
              }
                 
            ]`
im getting [object Object] .

**Comment by ZAYEC77** [comment]
Hey
Please, check issue #13 
If it doesn't help -- notify here

**Comment by rupalgohel** [comment]
Hello @ZAYEC77 ,

I have to create no of functions for every field. 
```
fucntion getAuthorFullName() 
{
  return $this->author->getFullName();
}
```
It should not be the right way to do.  Can  you suggest me some other way to achive this?

**Comment by ZAYEC77** [comment]
I think it's a possible solution.
Beside this, you can try to use `render` attribute to generate js code of column.

**Comment by rupsk1607** [comment]
I am not getting your suggestion to render attribute. Can you elaborate plz?

**Comment by ZAYEC77** [comment]
Please, read the documentation.

You can use `render` attribute this way.
```php
//config ...
    'columns' => [
        'id',
        //...
        [
            'class' => 'nullref\datatable\LinkColumn',
            'render' => new JsExpression('function render(data, type, row, meta ){
                return row["custom_field"];
            }'),
        ],
    ],
//...
```

but you need to pass data to your model.
You can use `afterFind` method or something like this.

**Comment by ZAYEC77** [comment]
But I prefer to implement custom getters for related fields. 
This way looks clear.
