### ISSUE TITLE
Error while retriving custom generated field with ajax

### ISSUE THREAD

**Issue by Matvik** [NullRefExcep/yii2-datatables#40]
I have extended column configuration like
```
[
                'label' => 'Name', 
                'value' => function($data) { 
                     return = $data->name
                },
            ], 
```
And serverSide is set to true.
It is work fine at simple column config, but custom column generates datatables error in alert window `DataTables warning: table id=w1 - Requested unknown parameter '0' for row 0`

**Comment by ZAYEC77** [comment]
Hello @Matvik 
Maybe you could try solution like this:
```php
'columns' => [
        'name',
],
```

**Comment by Matvik** [comment]
Yes, but this is only example, and i want to be free when showing data in table, as it is when using regular yii 2 grid view table.

**Comment by ZAYEC77** [comment]
We didn't provide syntaxes form your example
Please, check the readme.
If you want some custom stuff, you could implement own class with custom logic.
You could check [LinkColumn](https://github.com/NullRefExcep/yii2-datatables/blob/master/src/LinkColumn.php) as example.

If you think it could be useful for anyone else -- feel free with PR.

**Comment by Matvik** [comment]
Ok, thank you

**Comment by ZAYEC77** [comment]
Sure, your welcome)
Please, close issue, if you don't have others questions.
