### ISSUE TITLE
Reference the DataTable initialization to a global variable

### ISSUE THREAD

**Issue by skiiiks** [NullRefExcep/yii2-datatables#43]
Many of the DataTables advanced usage needs to refer to Datatable instance as the variable used to create the object.

In your "run" method, instead of using this:

`$this->getView()->registerJs('jQuery("#' . $id . '").DataTable(' . Json::encode($this->getParams()) . ');');`

you should use this:

`$this->getView()->registerJs('var ' . $id . ' = jQuery("#' . $id . '").DataTable(' . Json::encode($this->getParams()) . ');');`

So you can use the variable $id in Javascript to refer to the Datatable instance.

**Comment by ZAYEC77** [comment]
registerJs wraps code by closure
so you can't access to this var from global space
but you could get instance of Datatable by it id

**Comment by skiiiks** [comment]
In some cases I've found that when I refer to $("#id") it gives me this error: https://datatables.net/manual/tech-notes/3

Mainly when I'm in actions, init, and other advanced DataTable events.
But when I use the "global variable" (generated with the change I suggested) I have no problems ;-)

I don't know ... it's a unharmful change :-P

**Comment by ZAYEC77** [comment]
@skiiiks 
Actually, we could provide some additional property for the widget.
e.g.`globalVariable`
What do you think about it?

**Comment by skiiiks** [comment]
That would be perfect and cleaner ... I used to use the same variable name as the "id" (make sense), but maybe others could need different naming.
;-)

**Comment by ZAYEC77** [comment]
could you check my last changes at your environment?
https://github.com/NullRefExcep/yii2-datatables/commit/e5298db7be4a729245ff5083e779e1dfc4f5d3d6

**Comment by skiiiks** [comment]
Wow !!! I was using the Packagist version and it seems is an old one !!! I don't have DataTableColumn and there's a lot of new code for sorting columns ...  :-D

**Comment by ZAYEC77** [comment]
if it works as should I'll release new version asap.

**Comment by skiiiks** [comment]
As far as I have tested, it's ok ... and I use it hard way , but I'd like to test with the new features I didn't enjoy :-D   please, update packagist and I'll do other tests

**Comment by ZAYEC77** [comment]
you could test code from the master branch
you need to use `dev-master` version in your `composer.json` file
https://getcomposer.org/doc/articles/aliases.md

**Comment by ZAYEC77** [comment]
@skiiiks do you have a chance to check this feature?

**Comment by ZAYEC77** [comment]
I have tested this feature with the last code from master. It works.
