### ISSUE TITLE
Some basic questions of use and problems with the last version

### ISSUE THREAD

**Issue by skiiiks** [NullRefExcep/yii2-datatables#44]
1) How can I define the HTML attributes for the column cells ?
I mean, if I want to put data-attributes, or css classes, ...

2) How can I define, for example, the orderSecuence in the "aoColumns" DataTable ?

3) In the version you had in packagist, I can set orderable and orderSequence in the columns, now I can't

4) In this code    
```
          return [
             'datatables' => [
                 'class' => 'nullref\datatable\DataTableAction',
                 'query' => MyModel::find(),
                 'applyOrder' => function($query, $columns, $order) {
                    //custom ordering logic
                    return $query;
                 },
                 'applyFilter' => function($query, $columns, $search) {
                    //custom search logic
                    return $query;
                 },                 
             ],
         ];
```

how the ordering and search logic works ? Any example, I can not figure out how to manage $query, $columns and $oder/$search.

Is there any other documentation or advanced examples ?

5) When using LinkColumn, neither label nor title works and the column label appears empty ... how can I put the label/title ?

Thank you

**Comment by ZAYEC77** [comment]
1. this package didn't provide the ability for this feature
2. looks like it's a question at Datatable
3. looks like it's an issue at Datatable
4. https://github.com/NullRefExcep/yii2-datatables#server-side-processing
you could implement ordering and filtering logic by yourself in corresponding functions (`applyOrder` and `applyFilter`)
5. https://github.com/NullRefExcep/yii2-datatables#add-links-to-row
if with way doesn't work, please post issue

Please, don't use the issue for questions
Use it only for the issue or the enhancement requests
Feel free to contact me by email

**Comment by ZAYEC77** [comment]
as a basic example of `applyOrder` and `applyFilter` you could use method at `DataTableAction`:
https://github.com/NullRefExcep/yii2-datatables/blob/master/src/DataTableAction.php#L171
https://github.com/NullRefExcep/yii2-datatables/blob/master/src/DataTableAction.php#L195
