### ISSUE TITLE
Using 'title' in LinkColumn shows an error

### ISSUE THREAD

**Issue by skiiiks** [NullRefExcep/yii2-datatables#45]
Hi:

when using 'title' attribute in LinkColumn (to customize the name of the column) 

```
            'class' => 'nullref\datatable\LinkColumn',
            'render' => new JsExpression('function render(data, type, row, meta ){
                return "<a href=\"/custom/url/"+row["id"]+"\">View</a>"
            }'),
            'title' => 'My title'
```

shows this error:

Unknown Property – yii\base\UnknownPropertyException
Setting unknown property: nullref\datatable\LinkColumn::title

**Comment by ZAYEC77** [comment]
@skiiiks I guess caused that you don't have `id` field in your data.
Please, check it.

**Comment by ZAYEC77** [comment]
@skiiiks and if you check doc, we used property `label`:
https://github.com/NullRefExcep/yii2-datatables#add-links-to-row

**Comment by skiiiks** [comment]
It's not that ... I'm really sorry I didn't paste the whole code, but I'm using "id" in all the column definitions ;-)

I paste it complete:

```
echo DataTable::widget([
                'id' => 'main_datatable',
                'globalVariable' => 'main_datatable_2',
                'serverSide' => true,
                'processing' => true,
                'ajax' => '/cards/datatables',
                'tableOptions' => [
                    'class' => 'table table-hover datatable-highlight table-togglable',
                ],
                'columns' => [
                    'id',
                    'name',
                    'email',
                    [
                        'data' => 'card',
                        'class' => 'nullref\datatable\LinkColumn',
                        'render' => new JsExpression('function render(data, type, row, meta ){
                            return "<a href=\"/custom/url/"+row["card"]+"\">View</a>";
                        }'),
                        'title' => 'My card'
                    ],                    
                ],
            ]);

```

**Comment by ZAYEC77** [comment]
so, try to update package to last dev-master version, it should works even without id at columns definition

**Comment by ZAYEC77** [comment]
remove render and change title to label.

**Comment by skiiiks** [comment]
But if I need custom "render", can I use it also ?

**Comment by ZAYEC77** [comment]
if you use render you don't need label, i guess you understand why )

**Comment by skiiiks** [comment]
I think there's a misunderstanding ... my problem is not using label/render ... but using "title". What I need is to CUSTOM the title of the column

**Comment by ZAYEC77** [comment]
you just need to use label property

**Comment by skiiiks** [comment]
I think I'm not being clear ... SORRY
The title of the column is the first heading row with the name of the fields ... (name, email, ...)
If I use "label", that does not show what I put ... it shows nothing, clear, empty
If I use "title" (as it is working when you don't use LinkColumn), then it works.

Again, when I'm NOT using LinkColumn class, I can use "title", and what I put in "title" it will show in the first heading row, as the title of the whole column, instead of showing (by default) the "id".

But when I use the LinkColumn class (because, for example, I need to use custom "render"), then if I use "title" shows an error, and if I use label shows empty space.

**Comment by skiiiks** [comment]
Examples:

This shows a column data of "id" values with a heading title: "id"
```
                'columns' => [
                    'id',
                ],
```

This shows a column data of "lastname" values with a heading title: "Apellido"
```
                    [
                        'data' => 'lastname',
                        'title' => 'Apellido',
                    ],
```

This shows a column data of "lastname" values, with a heading title: "Apellido"
```
                    [
                        'data' => 'lastname',
                        'title' => 'Apellido',
                    ],
```

This shows a column data of "idcard" values, with a heading title: "idcard"
```
                        'data' => 'idcard',
                        'class' => 'nullref\datatable\LinkColumn',
                        'render' => new JsExpression('function render(data, type, row, meta ){
                            return "<a href=\"/custom/url/"+row["idcard"]+"\">View</a>"; // return row["idcard"] + " X ";
                        }'),
```

This shows the error written in this original thread
```
                        'data' => 'idcard',
                        'class' => 'nullref\datatable\LinkColumn',
                        'render' => new JsExpression('function render(data, type, row, meta ){
                            return "<a href=\"/custom/url/"+row["idcard"]+"\">View</a>"; // return row["idcard"] + " X ";
                        }'),
                       'title' => 'My card'
```

This shows a column data of "idcard" values, with a heading title: EMPTY
```
                        'data' => 'idcard',
                        'class' => 'nullref\datatable\LinkColumn',
                        'render' => new JsExpression('function render(data, type, row, meta ){
                            return "<a href=\"/custom/url/"+row["idcard"]+"\">View</a>"; // return row["idcard"] + " X ";
                        }'),
                       'label' => 'My card'
```

**Comment by ZAYEC77** [comment]
ok, now it looks clear, i need check it by myself

**Comment by ZAYEC77** [comment]
![image](https://user-images.githubusercontent.com/4509483/57971023-4a94df00-7991-11e9-8262-3c36ca119b70.png)

it works for me this way:
```php
    'columns' => [
        'price',
        [
            'class' => \nullref\datatable\LinkColumn::class,
            'title' => 'Header title',
            'label' => 'Link title',
            'url' => 'view',
        ]
    ],
```

**Comment by skiiiks** [comment]
it doesn't for me and I have the latest github repository.
also, please, try it with "data"
try 

```
        [
            'data' => 'price'
            'class' => \nullref\datatable\LinkColumn::class,
            'title' => 'Header title',
        ]
```

or even

```
        [
            'data' => 'price'
            'class' => \nullref\datatable\LinkColumn::class,
            'title' => 'Header title',
            'render' => new JsExpression('function render(data, type, row, meta ){
                            return "<a href=\"/custom/url/"+row["price"]+"\">View</a>"; // return row["price"] + " X ";
                        }'),
        ]
```

**Comment by ZAYEC77** [comment]
Try to update package one more time
As an additional example, you could check my project:
https://github.com/ZAYEC77/cat-with-eav
