### ISSUE TITLE
Add attributes to each column's cells

### ISSUE THREAD

**Issue by skiiiks** [NullRefExcep/yii2-datatables#46]
Hi:

I'd like to add some attributes to each column's cells ... I think I have here what you'd need (it's tested and working):

In DatatableColumn.php add another public variable:

```
public $htmlOptions;
```

In Datatable.php , at the end of method run():

```
if (isSet($this->_options['htmlOptions'])) {
            $js = "";
            foreach ($this->_options['htmlOptions'] as $key => $data) {
                $column = $key + 1;
                $attrs = "";
                foreach ($data as $attribute => $value) {
                    $attrs .= ".attr('".$attribute."', '".$value."')";
                }
                $js.= "jQuery('#".$id." tbody tr td:nth-child(".$column.")').each(function() { $(this)".$attrs."; });";
            }

            $this->getView()->registerJs(
                        <<<JS
{
                        $('#${id}')
                            .on( 'init.dt', function () {
                                $js
                            });

}
JS
            );


        }
```

So then you can for example add htmlOptions in the columns definition:

```
'columns' => [
                    [
                        'data' => 'id',
                        'title' => 'Id',
                        'htmlOptions' => [
                            'class' => 'otherClass'
                        ]
                    ],
                    [
                        'data' => 'email',
                        'title' => 'Email',
                        'htmlOptions' => [
                            'class' => 'myClass',
                            'data-anything' => 'something'
                        ]
                    ],
     ...
```

This will generate this:

```
$('#my_datatable').on( 'init.dt', function () {
   jQuery('#my_datatable tbody tr td:nth-child(1)').each(function() { $(this).attr('class', 'otherClass'); });
   jQuery('#main_datatable tbody tr td:nth-child(7)').each(function() { $(this).attr('class', 'myClass').attr('data-anything', 'something'); });
});

```

**Comment by ZAYEC77** [comment]
feel free to create ordinary PR

**Comment by skiiiks** [comment]
I'm really sorry, but I'm not good enough in git to do that :-D
but I'll try ;-)

**Comment by ZAYEC77** [comment]
could you explain why you need this feature?

**Comment by skiiiks** [comment]
To be able to interact and style the data cells ... it's something doable apart from this plugin, but it would be nice to have it integrated as other things ;-)

**Comment by ZAYEC77** [comment]
You could styling columns by CSS selectors e.g. `:nth-child` or other pseudo-classes.
Since as our widget support server-side data fetching, this feature could be difficult to implement for this case.
For your particular case, you could extend our widget class and implement custom logic at your own child class and use it.

**Comment by ZAYEC77** [comment]
Also, you could use `nullref\datatable\DataTableColumn` class to implement custom render logic by defining `render` property.
Please, check docs for more info about it.

**Comment by ZAYEC77** [comment]
@skiiiks
Please, check new version of the package:
https://github.com/NullRefExcep/yii2-datatables/releases/tag/v1.1.0 

I'll add property `sClass` to have ability to pass CSS class for the column cells.
