### ISSUE TITLE
Unknow column name

### ISSUE THREAD

**Issue by AFSIDD** [NullRefExcep/yii2-datatables#48]
Setting unknown property: nullref\datatable\DataTableColumn::name

'columns' => [
                                    'consumer',
                                    [
                                        'data'  => 'branchName', 
                                        'title' => "Branch Name", 
                                        'name'  => 'branchId'
                                    ],
]

Can you help with this? Currently on this version v1.1.0.

**Comment by ZAYEC77** [comment]
we didn't support property `name`, please check readme

**Comment by AFSIDD** [comment]
It worked with the previous version, although i get your point that you never supported name property before also. 
Is there a work around?

**Comment by ZAYEC77** [comment]
you could try to add `class` property to your column definition:
```
'columns' => [
  'consumer',
  [
    'class' => 'nullref\datatable\DataTableColumn',
    'data' => 'branchName',
    'title' => "Branch Name",
    'name' => 'branchId'
  ],
],     
```

**Comment by ZAYEC77** [comment]
I guess we have this exception at old version too, but you could check it to download v1.0.4.
We have "magic" __set/__get for DataTable class but it was never for DataTableColumn.

**Comment by AFSIDD** [comment]
Nope, adding class doesn't help also, i will try going back to 1.0.4 and recheck.

Thanks.
