### ISSUE TITLE
Column Definitions do not work after upgrade to 1.1.0

### ISSUE THREAD

**Issue by ChristophFoerste** [NullRefExcep/yii2-datatables#52]
Hi and thank you for your awesome work!

I recently upgraded to the latest version of your widget and recognized that some column definitions I was using before do not work any longer. In detail: "type", "searchable", "sortable", "width", "visible" and I do not find out how to make it work again.

Please find some code (the commented  sections do not work, one defintion as example).

> 'data' => 'id',
        'title' => 'Column Title',
        //'type' => 'num',
        //'searchable' => false,
        //'sortable' => false,
        //'visible' => false,
        //'width' => '140',
        'render' => new JsExpression('
                function ( data, type, full, meta ) {
                    return data                 
                }'
        ),`

It would be cool to get some tips on how to use these definitions again.

Kind regards
Chris

**Comment by ChristophFoerste** [comment]
Seems to work if the defintions are moved to "columnDefs"-attribute within the widget-options.

> 'columnDefs' => [
                   ['targets' => 0, 'width' => 90,  'searchable' => true,  'type' => 'num',    'sortable' => true,  'visible' => true,]
]

**Comment by ZAYEC77** [comment]
Hello @ChristophFoerste 
could you check which version of Datatables did you use?

**Comment by ChristophFoerste** [comment]
Sorry for the late reply.

I am using 1.10.19 of DataTables. The error was thrown in "DataTableColumn" class of your widget, stating the the attribute for "width" does not exist.

I do not have more details, because I am on the road right now.

Kind regards
Chris

**Comment by ZAYEC77** [comment]
I guess, we didn't support attributes like "searchable", "sortable", "width", "visible" even before.
But if I'm wrong, please check the previous version of the package and notify me which version works correct.

**Comment by Radon8472** [comment]
I have similar problems, I a already working on a bugfix for this.

**Comment by Radon8472** [comment]
I found the problem...

Before 41c2ee8 all custom config was silently passed to DataTables js-config.
In 41c2ee8 `DataTableColumn` was added, and all custom config properties are passed to this class, which currently only supports a few of the properties that DataTables supports.

What results in errors like this:

> Exception (Unknown Property) 'yii\base\UnknownPropertyException' with message 'Setting unknown property: nullref\datatable\DataTableColumn::type'
