### ISSUE TITLE
custom value

### ISSUE THREAD

**Issue by jackkusuma** [NullRefExcep/yii2-datatables#58]
Hi!
Amazing package ;)

I've tried to activate the serverSide but i don't know custom value in column widget when i use code

[
       'data' => function ($model){
           return date_formate(date_created($model->time_created,"Y-m-d"));
        },
       'title' => \Yii::t('app', 'date'),
       'filter' => ['true' => 'Yes', 'false' => 'No'],
],

that not working, so how to use that if i want to custom like that?

Thank you

**Comment by ZAYEC77** [comment]
Hello, where did you see such code?
`data` property at `DataTableColumn` could be only the string

**Comment by jackkusuma** [comment]
okay
