### ISSUE TITLE
yii2 datatables style settins problem.

### ISSUE THREAD

**Issue by Jonston** [NullRefExcep/yii2-datatables#64]
I'm trying to connect bootstrap styles to a widget in settings web.php
```php      
'assetManager' => [
            'bundles' => [
                'nullref\datatable\assets\DataTableAsset' => [
                    'styling' => DataTableAsset::STYLING_BOOTSTRAP,
                ]
            ],
            'appendTimestamp' => true,
],
```
but i get:
`Fatal error: Uncaught Error: Class 'nullref\datatable\assets\DataTableAsset' not found`
What i am doig wrong.
Help plz.
Thank you!

**Comment by ZAYEC77** [comment]
Hey 👋  
did you install `yii2-datatables` package?

**Comment by Jonston** [comment]
> Hey 👋
> did you install `yii2-datatables` package?

Of course.And it work.But i have this problem.

**Comment by ZAYEC77** [comment]
And do you have files in your vendor folder?

**Comment by Jonston** [comment]
> And do you have files in your vendor folder?

Composer packages are installed there.Including yii2 datatables.Project configurations are loaded before the Yii application is initialized in `web/index.php`.
```php
<?php

if (substr($_SERVER['HTTP_HOST'], 0, 4) === 'www.') {
    $nonWwwUrl = 'https://' . substr($_SERVER['HTTP_HOST'], 4);
    if (!empty($_SERVER['REQUEST_URI'])) {
        $nonWwwUrl .= '/' . $_SERVER['REQUEST_URI'];
    }
    header('Location: ' . $nonWwwUrl);
    exit;
}

$local = include_once(__DIR__ . '/../config/local.php');
$web = require_once(__DIR__ . '/../config/web.php');
if (empty($local)) {
    die('config/local.php not found');
}

require_once(__DIR__ . '/../vendor/autoload.php');
require_once(__DIR__ . '/../vendor/yiisoft/yii2/Yii.php');

$config = yii\helpers\ArrayHelper::merge(
    $web,
    $local
);

(new yii\web\Application($config))->run();
```
That's why auto-loading doesn't work.

**Comment by ZAYEC77** [comment]
So, is your issue resolved?

**Comment by Jonston** [comment]
> So, is your issue resolved?

How do I fix this error?The documentation says about require boostrap styles, but it turns out that the documentation is incorrect?

**Comment by ZAYEC77** [comment]
maybe the problem is in your config / autoloading?

**Comment by hoaaah** [comment]
> > So, is your issue resolved?
> 
> How do I fix this error?The documentation says about require boostrap styles, but it turns out that the documentation is incorrect?

Docs are correct actually. Use this package ini bootstrap 4 and it works like charm.
My config:
```php

                'nullref\datatable\assets\DataTableAsset' => [
                    'baseUrl' => '@web',
                    'js' => [
                        'datatables-bootstrap4-bundle/datatables.min.js'
                    ],
                    'css' => [
                        'datatables-bootstrap4-bundle/datatables.min.css',
                    ],
                    'styling' => false,
                ]
```

**Comment by ZAYEC77** [comment]
Looks like issue is resolved :)
