### ISSUE TITLE
Add bootstrap 4 support

### ISSUE THREAD

**Issue by Radon8472** [NullRefExcep/yii2-datatables#66]
Current Yii2 template uses bootstrap4 and so you get the error `Failed to instantiate component or class "yii\bootstrap\BootstrapAsset"`.

You can change this in `DataTableBootstrapAsset.php` when you replace the line

```php
$this->depends[] = 'yii\bootstrap\BootstrapAsset';
```

with

```php
$this->depends[] = 'yii\bootstrap4\BootstrapAsset';
```

Unfortunalle there is no bootstrap 4 in `@bower/datatables-plugins/integration/bootstrap` and I the source repo of [bower-asset/datatables-plugins](https://asset-packagist.org/package/bower-asset/datatables-bootstrap-plugin) seems to be removed or switched to private.

You should:
- find a way to load bootstrap 4 assets (either from newer version of "bower-asset/datatables-plugins" of another source) - e.g. [bower-asset/datatables.net-bs4](https://asset-packagist.org/package/detail?fullname=bower-asset/datatables.net-bs4)
- Add a switch into `DataTableBootstrapAsset` that checks if the current yii uses bootstrap4 or older and depending on the result choose from wich namespace "BootstrapAsset" dependecy is set

**Comment by ZAYEC77** [comment]
I'm not sure that we have free cycles for this right now
@Radon8472 feel free to create PR 🙏

**Comment by Radon8472** [comment]
> I'm not sure that we have free cycles for this right now @Radon8472 feel free to create PR 🙏

I already tested some possible solutions, I try to create a PR over the next weekend

**Comment by Radon8472** [comment]
@ZAYEC77  Pull Request is created see #67
