### ISSUE TITLE
Tabletool Extension 

### ISSUE THREAD

**Issue by nadrianm** [NullRefExcep/yii2-datatables#8]
Hello budy, I'm working with DataTables in a Yii2 Advanced Application, and I was wondering If I could integrate TableTools Extension with your plug-in. Do you know how to do it? If there is another way to do data export (PDF, CSV, ...) I will be grateful if you give me an example.

Here is the extension doc. https://www.datatables.net/extensions/tabletools/

I'm looking forward to hearing from you!

**Comment by ZAYEC77** [comment]
Hello, can You call widget with necessary parameters?
E.g:

``` php
<?= \nullref\datatable\DataTable::widget([
    'data' => $dataProvider->getModels(),
    'tableTools'=>['sSwfPath'=>'/swf/copy_csv_xls_pdf.swf'],
]) ?>
```
